### PR TITLE
Make recyclableMemoryStreamManager internal

### PR DESCRIPTION
**Pull request by kerams**
Keep seeing this in Intellisense when it's the one in my codebase I want to use.

### CODE REVIEW

**Comment by kerams** [comment]
The build failure is probably https://github.com/giraffe-fsharp/Giraffe/issues/513.

**Comment by Banashek** [comment]
With the merge of [517](https://github.com/giraffe-fsharp/Giraffe/pull/517) I think this should be able to pass the build if re-run now.

**Review by slang25 — APPROVED** [review]
Looks good 🙂

**Review by TheAngryByrd — APPROVED** [review]

**Comment by TheAngryByrd** [comment]
Thanks!

**Pull request merged**
