### PR TITLE
Add unsafe version of routef to Toke Router

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Adds to Token Router version of `routef` that doesn't perform checking of format on the runtime.

### CODE REVIEW

**Comment by dustinmoris** [comment]
@Krzysztof-Cieslak Thanks for the PR. What is the thinking behind having `routefUnsafe`? The way @gerardtoconnor added the validation it gets validated only once during startup and never again afterwards, so every time a http request comes in it will not do the validation again. If we go with this change I'd suggest to rename it to something different because "unsafe" sounds a lot scarier that what `routefUnsafe` is about and it has a lot of other meaning in .NET which could cause confusing for Giraffe users.

**Comment by Krzysztof-Cieslak** [comment]
I’m building router dynamically and the only way to abstract over different instances of `PrintFormat` is to use `obj` as a result type and unbox result on runtime.

Happy to change the name, open for suggestions.

**Comment by Krzysztof-Cieslak** [comment]
Ping ;)

**Comment by gerardtoconnor** [comment]
Hi, can you give some code examples of what you are trying to do so we can figure out safe performant alternative as working with obj should be last resort given the type safety sacrificed

**Comment by dustinmoris** [comment]
Hey, if you still need this functionality, could you please [open a new issue here](https://github.com/giraffe-fsharp/Giraffe.TokenRouter) now?

**Pull request closed without merging**
