### PR TITLE
Added attributes module

### PR DESCRIPTION
**Pull request by nojaf**
As originally discussed in https://github.com/giraffe-fsharp/Giraffe/issues/138 I'd like to add the html attributes. I've put them in a separate module but did add a prefix to clashing names.
I think it will be more practical to work with than module alias tricks.

### CODE REVIEW

**Comment by dustinmoris** [comment]
Hey, thanks for this PR.

Do you think we could maybe slightly change the names of the attributs? What I don't like about the current names is that there is three different variations how one attribute might have been defined, but only one will work and a user won't know unless they have looked it up or tried it out:

- `class`
- ```class```
- `class_attr`

Ideally I would like to have one consistent way of declaring all attributes. Maybe we could prepend an underscore to all of them?

Example:

`_class`, `_data`, `_acceptCharset`, etc. 

Attributes like `accept-charset` I would therefore also prefer to write in camel case so that we don't have to use ```` part of the name. What do you think, would an additional underscore everywhere feel weird?

**Comment by nojaf** [comment]
Good point, changed the names.

**Comment by dustinmoris** [comment]
Nice thank you, I think this looks really good now! One last question, what do you think of adding the `[<AutoOpen>]` attribute above the `Attributes` module? This would have the effect that if someone opens `open Giraffe.GiraffeViewEngine` that they will also have the `Giraffe.GiraffeViewEngine.Attributes` open without having to write the second open statement.

Just to be clear, I am not suggesting that this is what we should do, just putting it out there for consideration and wanting to know if you think this would be useful? I've done this with other modules in a recent release. For example most of the default functionality can be opened with a single `open Giraffe` now, so maybe a single `open Giraffe.GiraffeViewEngine` would be enough here as well?

**Comment by dustinmoris** [comment]
Also restarting the one failed Travis build.. looks like it was a hiccup with Travis which happens occasionally...

**Comment by nojaf** [comment]
Hmm, I guess it does seem handy to have the `[<AutoOpen>]`. I'll send a PR.

**Pull request merged**
