### PR TITLE
Create StreamReader inside task CE

### PR DESCRIPTION
**Pull request by hvester**
I believe that this should fix issue [177](https://github.com/giraffe-fsharp/Giraffe/issues/177). If the StreamReader is created without using task CE then it is disposed when the method returns the task that
might not be completed.

### CODE REVIEW

**Comment by dustinmoris** [comment]
Are you sure this is required? [It didn't have the task {} before](https://github.com/hvester/Giraffe/commit/ea395099c3d8bd88ab501ce224ed7705c23a9fac#diff-242b195e122369f466cfeb3a9810e4f3), but also I assigned the request body to a temporary variable, which might have made the difference.

Can you please try out [the NuGet package from the successful build](https://ci.appveyor.com/project/dustinmoris/giraffe/build/artifacts) before we merge and release another hotfix?

**Comment by forki** [comment]
The problem is that the streamreader is disposed at the end of the method.
And we read later. The fix is good. And mine was useless. -500 and -510 are
both broken

Am 19.12.2017 20:03 schrieb "Dustin Moris Gorski" <notifications@github.com

**Comment by forki** [comment]
But the good thing is we have a reproducible which repros 100 percent for
500 and 510. Do we can apply the fix and see if the hypothesis holds. And
we can't break something that is already broken ;-)

Am 19.12.2017 20:07 schrieb "Steffen Forkmann" <sforkmann@gmail.com>:

**Comment by dustinmoris** [comment]
Ok, as soon as the checks finished I'll do another release! Thanks for the super quick fix!

**Comment by gerardtoconnor** [comment]
Yeah surprised we didn't spot this sooner, the IDisposable interface is called as soon as initial reading Task is returned and the `use` variable looses scope, probably need to scan the codebase for any other cases of `use` outside task CE

**Comment by dustinmoris** [comment]
merged into master, new release coming any minute.

@gerardtoconnor Good idea, I did a quick search and the only other usage of `use` was with non async methods (like in tests), so this was the only occurrence.

**Comment by gerardtoconnor** [comment]
Can you review merge the parserValidator too while your at it so we can close related issues ?

**Comment by dustinmoris** [comment]
Sure, will do!

**Comment by forki** [comment]
Good news. It actually fixed the issue

**Pull request merged**
