### PR TITLE
Add explicitly the statement that the usage of `Giraffe.EndpointRouting` is recommended

### PR DESCRIPTION
**Pull request by 64J0**
## Description

With this PR I'm removing some empty spaces from the documentation and adding explicitly the statement that the usage of `Giraffe.EndpointRouting` is recommended.

## Related issues

* Close https://github.com/giraffe-fsharp/Giraffe/issues/534

### CODE REVIEW

**Review by TheAngryByrd — APPROVED** [review]
🎸 Thank you!

**Comment by TheAngryByrd** [comment]
@dustinmoris I somehow lost being able to merge again

**Comment by 64J0** [comment]
Up

**Comment by TheAngryByrd** [comment]
@dustinmoris I somehow lost being able to merge again

**Pull request merged**
