### PR TITLE
Adding ToIsoString method and unit tests

### PR DESCRIPTION
**Pull request by MorganW09**
New ToIsoString methods to resolve issue #367 around wrong date string being produced.

### CODE REVIEW

**Comment by MorganW09** [comment]
@slang25 Thanks for reviewing my change, do you have permission to merge this in?

**Comment by slang25** [comment]
Yes, I wanted to give others a chance to take a look and feedback. If we don't hear anything I'll merge later today 😃

**Comment by MorganW09** [comment]
Sounds good, thanks.

**Comment by slang25** [comment]
Thanks for the contribution, I'll get the release notes updated 😃

**Pull request merged**
