### PR TITLE
Create an html helper

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by dustinmoris** [comment]
hey sorry that you guys couldn't merge due to the missing required check. The problem was that on the master branch it needs an additional check and all pull requests should be made against `develop` instead, then @gerardtoconnor and the other maintainers can completely independently merge. The `develop` branch is always the next upcoming fully tested/releasable version.

**Comment by dustinmoris** [comment]
It's not required for this PR, but if you want to help release new features quicker you can also extend the docs by documenting the new `html` handler, otherwise I'm happy to do it as I always check all merged PRs before a new release and then diligently go through the docs to keep them up to date.

**Comment by forki** [comment]
What kind of docs do we expect. The readme is now growing a bit out of
control right?

Am 16.12.2017 23:34 schrieb "Dustin Moris Gorski" <notifications@github.com
>:

It's not required for this PR, but if you want to help release new features
quicker you can also extend the docs by documenting the new html handler,
otherwise I'm happy to do it as I always check all merged PRs before a new
release and then diligently go through the docs to keep them up to date.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/giraffe-fsharp/Giraffe/pull/174#issuecomment-352216671>,
or mute the thread

**Comment by dustinmoris** [comment]
@forki I would have just added the html handler to the list of default handlers in the README. I know the readme is long and it feels "unusual", but I don't think its actually getting out of control. I try to keep a concise table of contents, which should hopefully help anyone to find what they are looking for, as it would be the same (a list of links) on any other form of documentation as well (wiki/ website) and on the plus side, since all of the docs are in the README in one big organised document people can easily search the entire docs with a simple CTRL+F and developers can make sure they didn't miss any docs to update once they did an CTRL+F in markdown. Actually I think it's an feature :)

**Comment by forki** [comment]
I think eventually there should be a website, with tutorials and samples
and so on. But not today and definitely not because of the html helper
function ;-)

Am 17.12.2017 08:05 schrieb "Dustin Moris Gorski" <notifications@github.com

**Comment by dustinmoris** [comment]
@forki Agreed, I have it on my list of todos. I think it might happen soon ;)

**Comment by gerardtoconnor** [comment]
I think would be good start if we could split out the MDs a bit for handlers and razor etc but probably would be nicest if we went to website eventually. Website would need to be on GitHub with PR rule that you update docs website when pulling in new features. I like how all the docs are in one place now but it is now getting just too big for one page on GitHub.

**Pull request merged**
