### PR TITLE
Add ability to Configure Endpoints via IEndpointConventionBuilder

### PR DESCRIPTION
**Pull request by mrtz-j**
## Description

This PR adds the ability to configure endpoints via the IEndpointConventionBuilder. This would enable us to reuse some of the built-in OpenApi generation to generate OpenApi schemas from code. It's possible by replacing the `MetadataList` with a `ConfigureEndpoint`, which can be utilized to capture additional information about the endpoint. 

I've taken inspiration from Oxpeckers [Routing](https://github.com/Lanayx/Oxpecker/blob/develop/src/Oxpecker/Routing.fs) which uses a similar approach.

## How to test

A working example provided in the [Giraffe.OpenApi](https://github.com/mrtz-j/Giraffe.OpenApi) repo, which utilizes this branch. It's based on the MinimalApi approach, with a more functional syntax. 

```fsharp
|> configureEndpoint _.WithName("Endpoint")
|> withOpenApi<unit, string>
```

In the [example](https://github.com/mrtz-j/Giraffe.OpenApi/blob/main/samples/EndpointRoutingApp/Program.fs) Swagger has been used to display the configured endpoints.

Endpoints can be added to the OpenApi documentation as follows: 

We have the type `FsharpMessage`, with XML-documentation:

```fsharp
/// <summary>
/// Fsharp Message type 
/// </summary>
type FsharpMessage = {
    /// <summary>
    /// Hello content
    /// </summary>
    /// <example>This is an Example</example>
    Hello: string
}
```

and the endpoints `/hello`

```fsharp
let endpoints = [
      GET [
            route "/hello" (json {Hello = "Hello from Giraffe"})
            |> configureEndpoint _.WithTags("helloGiraffe")
            |> configureEndpoint _.WithSummary("Fetches a Hello from Giraffe")
            |> configureEndpoint _.WithDescription("Will return a Hello from Giraffe.")
            |> addOpenApiSimple<unit, FsharpMessage>
]
```

which will be produce the view below: 

<details><summary>Endpoint and Type in Swagger</summary>
<p>

image

</p>
</details> 

And for extra references the whole app.

<details><summary>Swagger view of the endpoints.</summary>
<p>
image
</p>
</details> 

If it's accepted, I'll either publish `Giraffe.OpenApi` or make another MR for it here. 

## Related issues

- #488

### CODE REVIEW

**Comment by nojaf** [comment]
Hello, thank you for this PR!

I can't review the code as I'm not suited enough for that.
However, this looks interesting. If this gets accepted would you be ok with [Giraffe.OpenApi](https://github.com/mrtz-j/Giraffe.OpenApi) being part of the organization here? Seems like an interesting addition to the family. Just thinking out loud though.

//cc @64J0, @dbrattli

**Comment by mrtz-j** [comment]
> Hello, thank you for this PR!
> 
> I can't review the code as I'm not suited enough for that. However, this looks interesting. If this gets accepted would you be ok with [Giraffe.OpenApi](https://github.com/mrtz-j/Giraffe.OpenApi) being part of the organization here? Seems like an interesting addition to the family. Just thinking out loud though.
> 
> //cc @64J0, @dbrattli

Hi there,

Yes, I would be fine with it being part of the organization.

**Comment by 64J0** [comment]
Hi, thanks for the PR, seems pretty cool. I think I'll have some time to review it next week!

**Comment by voronoipotato** [comment]
Fantastic, looking at it I don't see any issues. Since this works it would mean a lot to many of us if this was merged.

**Comment by dbrattli** [comment]
Thanks for submitting this RP. I think this looks really great 😊  We should also update the documentation before merging. I'm trying to figure out if this is a breaking change or not i.e for compiled applications upgrading Giraffe to a newer version of the library. The `addMetadata` function has the same signature but still has changed to a more curried form, but the original is still curried so should this matter?

```fs
val addMetadata:
   metadata: obj ->
   endpoint: Endpoint
          -> Endpoint
```

to
```fs
val addMetadata:
   metadata: obj
          -> Endpoint -> Endpoint
```

I don't think it's a breaking change 🙈  but I'll let someone who knows F# better than me decide.

**Comment by 64J0** [comment]
Since it's dealing with a piece of code similar to what we have on [Oxpecker](https://github.com/Lanayx/Oxpecker), I'll ping @Lanayx so he knows about it too

**Comment by 64J0** [comment]
Tested the sample application locally, and it's working as described. Great PR!

Regarding the `addMetadata` signature change pointed by @dbrattli, I agree that it's not a breaking change. I also agree that it would be nice to have the documentation updated. Would you like to do it @mrtz-j?

**Comment by mrtz-j** [comment]
I've updated the `addMetadata` function to match the previous signature just in case 😅. I'd also be up for writing some documentation over the weekend, but it's also fine if one of you guys wants to.

**Review by 64J0 — APPROVED** [review]
We can add the documentation later with another PR. 

Btw, what I have in mind is:

- Some paragraphs explaining how to use this new feature;
- A new sample project.

**Comment by nojaf** [comment]
Thanks for the review @64J0. Can we ship this as an alpha?

**Comment by 64J0** [comment]
> Thanks for the review @64J0. Can we ship this as an alpha?

Sure @nojaf! I'll do it either today or tomorrow.

**Review by dbrattli — APPROVED** [review]
This is great, and should be a pretty safe change since there's no breaking change and all the configure endpoint stuff is ASP specific anyways. The PR just enables you to configure it.

**Pull request merged**
