### PR TITLE
 Fixes for handling nullables when binding query strings

### PR DESCRIPTION
**Pull request by colinbull**

### CODE REVIEW

**Comment by colinbull** [comment]
@dustinmoris  I assume this is an AppVeyor sdk error?

**Comment by dustinmoris** [comment]
Yup, that was an issue with AppVeyor, I think I found a way to fix it now. Thanks for this PR!

**Comment by colinbull** [comment]
No worries. Is this branch built to a nuget source anywhere?

**Comment by dustinmoris** [comment]
Yes, if it succeeds it will publish to the [AppVeyor NuGet feed](https://github.com/giraffe-fsharp/Giraffe#nightly-builds-and-nuget-feed). You can also download the NuGet package manually from the build page: https://ci.appveyor.com/project/dustinmoris/giraffe/build/artifacts

**Pull request merged**
