### PR TITLE
Add F# Analyzers

### PR DESCRIPTION
**Pull request by 1eyewonder**
## Description

I thought it would be beneficial if we were to add some analyzers to the project in order to catch some areas we might improve. This opens up some discussion/thinking for the maintainers to consider configuration and additional pipeline opportunities.

1. Do we want to add analyzers to the build pipeline/PR checks? [See docs](https://ionide.io/FSharp.Analyzers.SDK/content/Running%20during%20CI.html)
2. Are there specific analyzers we want to trigger errors/warning/ignore?

I don't have any strong opinions and just wanted to share some other cool opportunities we could try and add to this PR or others if desired.

## How to test

1. Run `dotnet tool restore`
4. Run `dotnet msbuild /t:AnalyzeSolution`
5. See all the suggestions
  image

## Related issues

I was looking through some issues and came across #577 which made me think of suggesting this.

### CODE REVIEW

**Comment by 64J0** [comment]
Hello @1eyewonder, thanks for opening this PR. I'll review it during this week. For now, what I'd say is:

> 1. Do we want to add analyzers to the build pipeline/PR checks?

This idea is interesting. It must be helpful for PR reviews. If you don't want to tackle it with this PR, we can do it later, no problem.

**Comment by 1eyewonder** [comment]
If we go ahead and tackle it within this PR, I am ok with it, but I think we'll have to coordinate. I believe the `GitHub Advanced Security` settings needed to be configured (see docs linked above).

A repo which I've seen this feature active on is [Fable](https://github.com/fable-compiler/Fable) 

Here are some additional links to provide visual/examples to the PR reviews since that seems to be the area of interest.
- [Example PR](https://github.com/fable-compiler/Fable/pull/3290)
- [GitHub Action Example](https://github.com/fable-compiler/Fable/blob/main/.github/workflows/build.yml#L223-L258)

**Comment by 64J0** [comment]
Ack, thanks for the additional material @1eyewonder! I'll try to take a proper look at this PR either this or next week.

**Comment by 64J0** [comment]
Cool, I think it's working:

image

**Review by 64J0 — APPROVED** [review]
Looks good to me

**Pull request merged**
