### PR TITLE
routeStartsWithf + routeStartsWithCif

### PR DESCRIPTION
**Pull request by dv00d00**
Added support for regular expression match mode
Added two extra routing extensions which are using it
Added some basic tests

Addresses #341

This is draft, comments are welcome

Edit: after looking at it for a while, I am pleased with the current state of pr, or I lost the ability for self-criticism

### CODE REVIEW

**Comment by dustinmoris** [comment]
This looks great! The new changes are very subtle but effective. I like it a lot.

**Comment by dv00d00** [comment]
Naming is hard though. I kept old tryMatchInput as it was public and added a replacemnt with options, wthout thinking much of its name 😄 . And such tryMatchInputOptions was born. I don't know how to fix it though, I can think of an overaload as a probable solution

**Comment by dv00d00** [comment]
Ok, overloading works on toupled methods on a class, not sure how to get away from breaking binary compatibility here and do not introduce a new name

**Comment by dv00d00** [comment]
I've done minor renaming + local perf tuning which would not affect much, except only it shall not make things worse than they were before refactoring

**Comment by dustinmoris** [comment]
Thanks for the extra changes. I was thinking about the naming too and I think `tryMatchInput` should be renamed to `tryMatchInputExact` as that is what it;s really doing with the only option being case sensitivity, whereas `tryMatchInput0` is what gives full flexibility and should therefore probably just be named `tryMatchInput`. This would be a breaking change, but the next upcoming release already has other minor breaking changes like this. If you agree then I will document it accordingly in the release notes. What do you think?

**Comment by dv00d00** [comment]
Sounds great @dustinmoris 
I will commit the renames and try to update docs where apropriate

**Comment by dv00d00** [comment]
Once we have started break things, maybe reorder arguments list and put string to the last position?
e.g.
Before
```fsharp
let tryMatchInput (format : PrintfFormat<_,_,_,_, 'T>) (input : string) (options : MatchOptions) 
```
After
```fsharp
let tryMatchInput (format : PrintfFormat<_,_,_,_, 'T>) (options : MatchOptions) (input : string) 
```

To allow easier partial application?

**Comment by dustinmoris** [comment]
Thanks for this PR! I've also swapped the arguments as I think that's a good suggestion!

**Pull request merged**
